name: 'Web Navigator Agent'
description: 'Autonomous web navigation agent using Gemma 3 270M'
inputs:
  website_url:
    description: 'The starting URL for the agent'
    required: true
  user_instruction:
    description: 'Instruction for the agent (e.g., "Login and summarize dashboard")'
    required: true
  model:
    description: 'Model variant to use'
    required: true
    default: 'gemma-3-270m-it'
  hf_token:
    description: 'Hugging Face Token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    
    - name: Set up Python
      shell: bash
      run: uv python install 3.10

    - name: Install Dependencies
      shell: bash
      run: |
        uv venv
        uv pip install -r ${{ github.action_path }}/../requirements.txt
        # Install playwright browsers
        # Note: uv run automatically detects and uses the .venv in the current directory
        uv run python -m playwright install chromium
        uv run python -m playwright install-deps chromium

    - name: Run Web Agent
      shell: bash
      env:
        HF_TOKEN: ${{ inputs.hf_token }}
        HF_HOME: ${{ github.workspace }}/hf_cache
        PYTHONPATH: ${{ github.action_path }}/..
      run: |
        uv run ${{ github.action_path }}/../web_agent.py \
          --url "${{ inputs.website_url }}" \
          --instruction "${{ inputs.user_instruction }}" \
          --model "${{ inputs.model }}"
